apiVersion: v1
kind: Service
metadata:
  name: {{ include "geth-plex.fullname" . }}
  labels:
    {{- include "geth-plex.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol | default "TCP" }}
  {{- end }}
  selector:
    {{- include "geth-plex.selectorLabels" . | nindent 4 }}
